services:
  app:
    build: AsyncApi
    ports:
      - "8000:8000"
    depends_on:
      - es01
  es01:
    image: elasticsearch:8.4.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.compression=true
      - http.max_content_length=500mb
      - xpack.security.enabled=false
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      - es01
  nginx:
    build: nginx_settings
    ports:
      - 80:80
    depends_on:
      - app
  redis:
    image: redis:6.2-alpine
    expose:
      - 6379
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local