services:
  app:
    build:
      context: ./AsyncApi
      dockerfile: Dockerfile
    image: app-image
    expose:
      - "8000"
    depends_on:
      - es01
      - redis01
    environment:
      - elastic_uri=http://es01:9200
      - redis_uri=redis://redis01:6379
      - service_url=http://app:8000
  tests:
    image: app-image
    depends_on:
      - app
    entrypoint:
      - "/bin/sh"
      - -ecx
      - |
          poetry install --only "test"
          poetry run python3 tests/functional/utils/wait_for_es.py
          poetry run python3 tests/functional/utils/wait_for_redis.py
          poetry run python3 tests/functional/utils/delete_schemas.py
          poetry run python3 tests/functional/utils/create_schemas.py
          poetry run pytest tests/functional/src

    environment:
      - elastic_uri=http://es01:9200
      - redis_uri=redis://redis01:6379
      - service_url=http://app:8000

  es01:
    image: elasticsearch:8.4.1
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.compression=true
      - http.max_content_length=500mb
      - xpack.security.enabled=false
  redis01:
    image: redis:latest
    expose:
      - 6379